name = "orange-meets"
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2024-10-07"
main = "./build/index.js"
compatibility_flags = ["nodejs_compat"]
[observability]
enabled = false

[site]
  bucket = "./public"

[vars]
CALLS_APP_ID = "READTALK_CALLS_APP_ID"

# Optional vars
# OPENAI_MODEL_ENDPOINT = ""

[[durable_objects.bindings]]
name = "rooms"
class_name = "ChatRoom"

# Indicate that you want the ChatRoom class to be callable as Durable Objects.
[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["ChatRoom"]

# The necessary secrets are:
# - CALLS_APP_SECRET
# To add secret, run `echo <VALUE> | wrangler secret put <NAME>`

# Optional secrets:
# OPENAI_API_TOKEN = ""

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1
