name = "calling"
compatibility_date = "2024-10-07"
main = "./build/index.js"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = "./public"

[vars]
CALLS_APP_ID = "READTALK_CALLS_APP_ID"

[[durable_objects.bindings]]
name = "rooms"
class_name = "ChatRoom"

[[migrations]]
tag = "v2"
new_sqlite_classes = ["ChatRoom"]

# Observability
[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1
